### PR TITLE
Add configuration options to Yubikey

### PR DESCRIPTION
**Pull request by wndxlori**

### CODE REVIEW

**Comment by ukd1** [comment]
@wndxlori the travis build failed on this; looks like you've used 1.9 style hashes?

**Comment by wndxlori** [comment]
I can fix it when I get home from the YYC.js meetup. 

Just a thought... Since 1.8.7 is EOL as of June, do we care?

**Comment by ChrisLundquist** [comment]
Yes. There are plenty of people still on 1.8.7 / REE. If it is easy to support it by not using syntactic sugar, then we should.

Food for thought, Centos doesn't have a ruby 1.9 package, you are forced to install from source via rvm / ruby_build or roll your own RPM.

**Comment by ukd1** [comment]
@wndxlori I agree with @ChrisLundquist; it sucks as I love the new sugar and yes it's nearly EOL, but people still use it and it's easy to support

**Comment by wndxlori** [comment]
Ok, you win :-) had to try, though. 

And, cool, I edited this and fixed from my ipad!

**Pull request merged**
