### PR TITLE
Fix SSL VERIFY_NONE

### PR DESCRIPTION
**Pull request by imajes**
obviously this is important for stuff like yubikey to be secure. Right now it's not even validating SSL certs. :(

this set of commits makes life better. (sorry about the white space ones)

### CODE REVIEW

**Comment by shawnjgoff** [comment]
I agreee that this gem must use `VERIFY_PEER`, and it's shocking that it isn't. This pull request has so much more that just isn't necessary, though. Just change `VERIFY_NONE` to `VERIFY_PEER`, and add a call to `OpenSSL::X509::Store#set_default_paths`. You might possibly add a way for a user to give a path to Yubico's certificate chain so that not all the certs in the system CA store are trusted.

**Comment by ukd1** [comment]
@shawnjgoff / @imajes I know this is quite an old pull request, but some of it seems useful still - would you be willing to update for the current version?

**Comment by maartenvg** [comment]
Now that 1.3.0 is more or less released, let's give this issue some love. 

I agree that we should boost the security of this module. If the original author ( @imajes ) is not able to finish this issue, I don't mind making it happen.

**Comment by shawnjgoff** [comment]
@ukd1 I won't have the opportunity to fix it.

**Comment by ukd1** [comment]
@shawnjgoff I understand!

@maartenvg :+1:

**Pull request closed without merging**
